service: bus-backend-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: ap-southeast-1
  environment:
    STAGE: ${opt:stage}
  vpc:
    subnetIds: ${self:custom.subnetPrivateId.${opt:stage}}
    securityGroupIds: ${self:custom.securityGroupId.${opt:stage}}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - 'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter/bus/*'

functions:
  get_buses:
    handler: buses.get
    memorySize: 128
    events:
      - http:
          path: api/buses
          method: get
  get_busstops:
    handler: busstops.get
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: api/bus-stops
          method: get
  get_arrival:
    handler: arrival.get
    memorySize: 128
    events:
      - http:
          path: api/arrival/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  update_busstops_cache:
     handler: update_cache.busstops
     memorySize: 128
     events:
       - schedule:
           name: fetch-latest-busstops-${self:provider.stage}
           description: fetch and update bus stops cache
           rate: rate(1 minute)
           enabled: true

plugins:
  - serverless-offline-scheduler
  - serverless-offline
  - serverless-python-requirements
  - serverless-ssm-publish

custom:
  ssmPublish:
    enabled: true
    params:
      - path: ${self:custom.apiGatewayKeyPath.${opt:stage}}
        source: ServiceEndpoint
        description: API Gateway endpoint url
        secure: true
  apiGatewayKeyPath:
    dev: /bus-backend-app/dev/apiGateway/endpoint
    staging: /bus-backend-app/staging/apiGateway/endpoint
    prod: /bus-backend-app/prod/apiGateway/endpoint
  subnetPrivateId:
    dev: ${ssm:/bus-backend-infra/dev/subnet/private/ids~split}
    staging: ${ssm:/bus-backend-infra/staging/subnet/private/ids~split}
    prod: ${ssm:/bus-backend-infra/prod/subnet/private/ids~split}
  securityGroupId:
    dev: ${ssm:/bus-backend-infra/dev/securityGroup/ids~split}
    staging: ${ssm:/bus-backend-infra/staging/securityGroup/ids~split}
    prod: ${ssm:/bus-backend-infra/prod/securityGroup/ids~split}
  
