name: Integrate

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract STAGE
      run: echo "STAGE=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: Rename STAGE to prod if master branch
      if: env.STAGE == 'master'
      shell: bash
      run: echo "STAGE=prod" >> $GITHUB_ENV
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    - name: Create env file
      run: | # cp sample.env.yml env.yml
        cat > env.yml << EOF
        ${{ secrets.ENV }}
        EOF
    - name: Deploy create domain
      run: sls create_domain -s ${{ env.STAGE }}
    - name: Deploy Lambda functions
      run: sls deploy -s ${{ env.STAGE }}
