name: Integrate

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw##*/}
        echo "STAGE=$branch" >> $GITHUB_ENV
    - name: Rename STAGE to prod if master branch
      if: env.STAGE == 'master'
      shell: bash
      run: echo "STAGE=prod" >> $GITHUB_ENV
    - name: Debug
      run: echo ${{ env.STAGE }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --stage ${{ env.STAGE }}
    - name: Create env file
      run: | # cp sample.env.yml env.yml
        cat > env.yml << EOF
        ${{ secrets.ENV }}
        EOF
    - name: Deploy Lambda functions
      run: sls deploy --stage ${{ env.STAGE }}
